### ISSUE TITLE
Migrate design document to this issue tracker

### ISSUE THREAD

**Issue by ctrueden** [fiji/Colocalisation_Analysis#21]
There is a detailed design document on the ImageJ wiki which covers many topics. This information should all be migrated to the issue tracker here, so that all the work is being tracked in a single place.

http://fiji.sc/Coloc_2_designNotes

**Comment by chalkie666** [comment]
@ctrueden i agree that as much as possible from that page should be moved into issues in the tracker. 
However, there is perhaps  a place for that document still, in order to collect half ideas and possibilities that haven't been thought through yet.... as a place to store the more weird and wonderful ideas that spring up and keep track of other software implementations and algorithms published in the literature, or that get dreamed up.  

Eg, there is no point in me adding an issue to the tracker called - "implement entropy based and multial information algorithms", as these are just ideas right now, we dint know ehat the maths really  looks like, and we havent figured out if they make sense or are useful,  let alone how to implement them. 

We also need a sandbox for sketching out ideas for the real GUI. The tracker wont really work for that???

but in principle i agree.. move as much as possible - clear cut obvious readily implementable v (and bug fixes)  that can and should be implemented without too much exploration research about the how and why etc.  
I already moved a bunch of stuff...

Do you have a better idea for a sandbox area for coloc ideas than a wiki page?

**Comment by ctrueden** [comment]
Maybe we could use the [wiki here on GitHub](https://github.com/fiji/Colocalisation_Analysis/wiki) for that?

The thinking on this is still evolving, and by no means set in stone, but the general idea is to put the "user-facing" docs on http://imagej.net/ and the "dev-facing" pages on GitHub wiki, where "dev" means "people coding on the plugin itself."

That said, there are probably lots of other examples of plugin-specific technical material on the ImageJ wiki right now, and migrating it is far from urgent—there is no immediate pragmatic win to doing so, after all. It would just help make things better organized (and less overwhelming for users browsing the ImageJ wiki) in the long term.

**Comment by ctrueden** [comment]
As for half-baked ideas in the issue tracker, I don't think it is necessarily a problem. The issue tracker serves several purposes see http://imagej.net/Issues#What_are_issues_for.3F for the main list. If your idea fits into any of those goals, then the issue tracker is good for it.

**Comment by chalkie666** [comment]
Hi Curtis

One thing is that I want interested non programmer,  scientific users who
could contribute info to be able to do so with out having to deal onto
Github and be frightened off....

Thoughts?

**Comment by ctrueden** [comment]
@chalkie666 If you truly feel that the wiki on GitHub is somehow scarier than the ImageJ wiki, then OK. Whatever you think is best is fine with me.

**Comment by chalkie666** [comment]
i can easily move the content to the github wiki pages for the
colocalisation analysis repo...., then indeed, its still just a wiki page
and not an atomised issue tracker.... so i will do that if its more
appropriate...
cheers

D

**Comment by chalkie666** [comment]
@ctrueden 
done 
https://github.com/fiji/Colocalisation_Analysis/wiki/DesignNotes
now i need to tidy the todo list at the bottom of the Coloc_2 imageJ.net wiki page, and move stuff here.

**Comment by ctrueden** [comment]
Thanks @chalkie666. I improved some of the formatting on that wiki page, though much more should ideally be done in the future to clean it up and streamline things. But great start!

**Comment by chalkie666** [comment]
Yes. It needs some work. I will address it soon as I can.
