### ISSUE TITLE
Results: warnings are not listed in the log window

### ISSUE THREAD

**Issue by chalkie666** [fiji/Colocalisation_Analysis#26]
but they should be, like for all other results output methods.

Perhaps need to make the log window output a real ResultsHandler implementation that is always run (or user selectable), rather than a hacked on set of IJ.log statements in loops.?

**Comment by chalkie666** [comment]
@etarena what do you think about making the IJ log output yet another results handler (like PDF output and the guy output)  as described above? Is it better than random sprinkling IJ log commands throughout the code?

**Comment by etarena** [comment]
@chalkie666 ... part of me thinks we should leave it for now - perhaps?  As we start converting to ImageJ2 - it will become a non-issue - no?  Though if you think it is still a worthwhile middle-step process... I can do it (maybe it would help streamline the conversion process?  i have no idea honestly.).  It's good for me in any case - since I'm still learning.
