### ISSUE TITLE
Results: add mask type: "none", "ROI" or "mask image" to results output 

### ISSUE THREAD

**Issue by chalkie666** [fiji/Colocalisation_Analysis#35]
make a new "String, String" result to put in the DataContainer for the type of ROI/mask used, 
so the user knows after the fact if they used a ROI or mask or not.

**Comment by etarena** [comment]
@chalkie666 - Does this refer to:

`// enumeration of different mask types
public enum MaskType { Regular, Irregular, None };`

So Regular, Irregular, and None represent the different mask statuses, "mask image", "ROI", and "none" respectively?  or am I missing something?  Then we can just include a String to indicate the maskType, ie String maskStatus?

**Comment by ctrueden** [comment]
There are advantages (and disadvantages) to strong typing rather than using `String`. Do the mask types be extensible? If not, they should probably stay as an enum. Otherwise, we could consider an "extensible enum" pattern; [here](https://github.com/imagej/imagej-common/blob/imagej-common-0.24.1/src/main/java/net/imagej/axis/Axes.java#L37-L40) is an example.

**Comment by ctrueden** [comment]
See also 8ff13666, which added the current mask type logic to `DataContainer` etc.
