### ISSUE TITLE
not able to run the plugin after installation

### ISSUE THREAD

**Issue by tushard1987** [fiji/Colocalisation_Analysis#63]
I could install the plugin master. It appeared in the plugin menu but error messege appeared stating that the source file is not up to date?!

**Comment by ctrueden** [comment]
Is there some reason you cannot use the version which ships with Fiji? Do you need bug-fixes which are on master but not yet released? Not that I will be cutting releases today or tomorrow.

If you want to test the latest snapshot, can you please describe what you tried? And post the exact error message? Please read over [Bug reporting best practices](https://imagej.net/Bug_reporting_best_practices).

**Comment by tushard1987** [comment]
Thank you for prompt reply. I really appreciateit. Could you please eleborate which version of Fiji has pre-installed coloc2? (if this is what you mean ships with fiji?)

**Comment by imagejan** [comment]
Coloc 2 is part of Fiji since years. You can find it in the menu using the [Command Finder](http://imagej.net/Using_the_Command_Launcher). It will show: *Analyze > Colocalization > Coloc 2*

**Comment by ctrueden** [comment]
From your screenshots, it looks like you followed a very nonstandard process, which ended up placing one or more `.java` files in your ImageJ directory structure somewhere. (Out of curiosity: did you follow a guide from somewhere? If so, it would be nice to update this guide so that its process actually works.)

If you are trying to modify the Coloc 2 source code and test your changes, then please see [this guide](https://imagej.net/How_to_contribute_to_an_existing_plugin_or_library) for instructions.

**Comment by tushard1987** [comment]
Ohh I found it. thank you. I got to know about the procedure here http://imagejdocu.tudor.lu/doku.php?id=howto:plugins:how_to_install_a_plugin
