### ISSUE TITLE
Results Dashboard v2: Improve results display

### ISSUE THREAD

**Issue by ctrueden** [fiji/Colocalisation_Analysis#8]
From Ann Wheeler:
> In the output results file one needs to know what slice and ROI the colocalisation coefficients correspond to and be able to only chose the ones of interest for the study .

Migrated-From: http://fiji.sc/bugzilla/show_bug.cgi?id=1100

**Comment by chalkie666** [comment]
using the maskHash integer ID as a unique identifier for ROIs and the jobName output is implemented in my latest changes, which @tomka is trying to merge into fiji master currently. But the imageJ ROI manager's ROI labels and these hash IDs are obviously not the same. The output images do show the selected ROI patch of image... so visually you can see which RIO of an image it is... but maybe we can do better.  
Possibly best to use the ROI manager labels as the ID of the roi and use that in the jobName, but that leaves the problem of image mask naming.... i guess the mask images has a name so that can be used, so long as the user knows to use unique named mask images?

**Comment by chalkie666** [comment]
this goes into the new "Results Dashboard v2" see issue #???

**Comment by tomka** [comment]
On Thu, Jul 30, 2015 at 02:45:06AM -0700, dan white wrote:
> using the maskHash integer ID as a unique identifier for ROIs and the
> jobName output is implemented in my latest changes, which @tomka is
> trying to merge into fiji master currently.

You merged the cleaned up branch already. So it is part of Coloc 2's
master branch. :-)

**Comment by chalkie666** [comment]
so its done! i will then close this one.
